name: Sanity CI (should pass)

on: workflow_dispatch

permissions:
  contents: write

jobs:
  ok:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create a file
        run: echo "It works 🎉" > OK.txt
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add OK.txt
          git commit -m "ci: sanity OK" || true
          git push
